openapi: 3.0.1
info:
  title: Gemini AI API
  description: API for generating text based on training data and a prompt.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000  # Adjust if your server is different

paths:
  /api/generate:
    get:
      summary: Generate text using the Gemini model.
      description: Takes training data and a prompt as input, generates text based on these.
      responses:
        200:
          description: Successful text generation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                    description: The generated text.
        400:
          description: Bad Request due to API key issue.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message related to the API key (e.g., "API key not found in .env file").
        404: 
          description: Not Found. Error occurred when parsing the AI response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message.
        500:
          description: Internal server error, likely due to an exception during text generation or data loading.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message.

  /{path}:
    get:
      summary: Serve static files
      description: Serves static files from the 'web' directory
      parameters:
        - name: path
          in: path
          description: Path to the static file
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful file retrieval
        404:
          description: File not found
